/* Full room/activity integration; only local Firebase fixtures are used. */
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const http = require('node:http');
const { pathToFileURL } = require('node:url');
const { chromium } = require('playwright');
const installFirebaseMock = require('./firebase-mock.js');
const root = path.resolve(__dirname, '..');
const mime = { '.js':'text/javascript', '.css':'text/css', '.html':'text/html', '.png':'image/png', '.jpg':'image/jpeg' };
const server = http.createServer((req,res) => {
  const file = path.resolve(root, '.' + decodeURIComponent(new URL(req.url,'http://localhost').pathname));
  if (!file.startsWith(root + path.sep)) { res.writeHead(403); return res.end(); }
  fs.readFile(file,(err,data) => { res.writeHead(err ? 404 : 200, {'Content-Type':mime[path.extname(file)] || 'application/octet-stream'}); res.end(err ? '' : data); });
});
(async () => {
  await new Promise(resolve => server.listen(0,'127.0.0.1',resolve));
  const origin = `http://127.0.0.1:${server.address().port}`;
  const browser = await chromium.launch({ channel:process.env.BROWSER_CHANNEL || 'chrome', headless:true });
  try {
    const context = await browser.newContext({ viewport:{width:1440,height:900} });
    await context.addInitScript(installFirebaseMock);
    await context.route(/^https?:\/\//, route => route.request().url().startsWith(origin) ? route.continue() : route.fulfill({status:200,contentType:'application/json',headers:{'access-control-allow-origin':'*'},body:'null'}));
    const page = await context.newPage();
    const errors = [];
    page.on('pageerror',e => errors.push(e.message));
    await page.goto(process.env.ACTIVITY_PROTOCOL === 'file' ? pathToFileURL(path.join(root,'index.html')).href : `${origin}/index.html`);
    await page.waitForFunction(() => document.documentElement.dataset.appReady === 'true');
    await page.click('#btn-go-login');
    await page.fill('#login-code','TEST-USER');
    await page.click('#btn-login');
    await page.waitForFunction(() => ChatApp.currentUser?.code === 'TEST-USER');
    await page.evaluate(() => ChatApp.openRoom('test',{quiet:true}));
    await page.waitForFunction(() => ChatApp.currentRoomId === 'test' && !ChatApp.bulkLoading);
    await page.fill('#msg-input','Chat survives activity mode');
    await page.evaluate(() => ChatApp.sendTextMessage());
    await page.waitForFunction(() => document.querySelector('#messages-inner').textContent.includes('Chat survives activity mode'));
    await page.evaluate(() => {
      window.__messagesBefore = document.getElementById('messages-inner');
      window.__messageBefore = document.querySelector('.msg-row');
      window.__roomRefBefore = ChatApp.roomOnlineRef;
      ChatApp.openRoomActivitiesModal();
    });
    assert.equal(await page.locator('#room-activities-menu').isVisible(),true);
    assert.equal(await page.locator('#modal').isVisible(),false);
    await page.evaluate(async () => {
      await __testDatabase.ref('users/PLAYER').set({username:'player',usernameLower:'player',displayName:'Live Player',displayNameLower:'live player',photoTransform:{s:1.6,xRel:.1,yRel:-.08}});
      await __testDatabase.ref('appPresence/PLAYER/device').set({idle:false,updatedAt:Date.now()});
      await __testDatabase.ref('rooms/test/online/PLAYER').set({username:'player',roomActivity:{id:'bopl-royale',title:'Bopl Royale',startedAt:Date.now()}});
    });
    await page.waitForFunction(() => document.querySelector('[data-activity-players="bopl-royale"]').textContent.includes('Live Player'));
    await page.evaluate(() => __testDatabase.ref('users/PLAYER/displayName').set('Updated Player'));
    await page.waitForFunction(() => document.querySelector('[data-activity-players="bopl-royale"]').textContent.includes('Updated Player'));
    assert.equal(await page.locator('.room-activity-player-avatar img').evaluate(el => parseFloat(getComputedStyle(el).left) === el.parentElement.clientWidth / 2),true,'avatar retains shared centered crop geometry');
    await page.screenshot({path:path.join(root,'../activity-menu.png')});
    await page.evaluate(() => __testDatabase.ref('rooms/test/online/PLAYER').remove());
    await page.waitForFunction(() => !document.querySelector('[data-activity-players="bopl-royale"]').textContent.includes('Updated Player'));
    await page.click('#room-activity-merge-party');
    await page.waitForFunction(() => document.querySelector('#games-frame')?.contentWindow?.__mergeParty);
    let game = page.frameLocator('#games-frame');
    assert.equal(await page.locator('#games-stage-head').isVisible(),false);
    assert.equal(await page.locator('#games-stage-fullscreen').count(),0);
    assert.equal(await page.locator('.chat-main').isVisible(),false);
    const full = await page.locator('#games-stage-wrap').boundingBox();
    assert.equal(Math.round(full.width),1440);
    assert.equal(Math.round(full.height),900);
    await game.locator('#activityChatBtn').click();
    await page.waitForFunction(() => document.body.dataset.activityChat === '1');
    assert.equal(await page.locator('#members-sidebar').isVisible(),false);
    assert.ok(await page.evaluate(() => __messagesBefore === document.getElementById('messages-inner') && __messageBefore === document.querySelector('.msg-row') && __roomRefBefore === ChatApp.roomOnlineRef));
    let box = await page.locator('.chat-main').boundingBox();
    assert.equal(Math.round(box.width),432);
    assert.equal(Math.round(box.x),1008);
    await page.fill('#msg-input','Draft retained while playing');
    await page.evaluate(() => ChatApp.toggleMembersListVisibility());
    let members = await page.locator('#members-sidebar').boundingBox();
    assert.equal(Math.round(members.width),432);
    assert.equal(Math.round(members.x),1008);
    await page.click('#activity-chat-members-back');
    const grip = await page.locator('#activity-chat-resize').boundingBox();
    await page.mouse.move(grip.x + grip.width / 2,grip.y + grip.height / 2);
    await page.mouse.down();
    await page.mouse.move(1152,450);
    await page.mouse.up();
    assert.equal(Math.round((await page.locator('.chat-main').boundingBox()).width),288,'drag resizes chat and activity together');
    await page.locator('#activity-chat-resize').focus();
    await page.keyboard.press('Home');
    box = await page.locator('.chat-main').boundingBox();
    assert.equal(Math.round(box.width),216);
    assert.equal(await page.locator('#msg-input').inputValue(),'Draft retained while playing');
    await page.evaluate(() => ChatApp.applySidebarPosition('left'));
    box = await page.locator('.chat-main').boundingBox();
    assert.equal(Math.round(box.x),0);
    await page.locator('#activity-chat-resize').focus();
    await page.keyboard.press('End');
    await page.screenshot({path:path.join(root,'../activity-chat-left.png')});
    await game.locator('#playBtn').click();
    await page.evaluate(() => {
      const frame = document.querySelector('#games-frame');
      frame.contentWindow.__mergeParty.debug.drop();
      frame.contentWindow.__mergeParty.debug.step(8);
      window.__mergeFrame = frame;
      window.__mergeWindow = frame.contentWindow;
    });
    await game.locator('#pauseBtn').click();
    assert.equal(await page.evaluate(() => __mergeWindow.__mergeParty.isPaused()),true);
    const paused = await page.evaluate(() => JSON.stringify(__mergeWindow.__mergeParty.debug.getState().balls));
    await game.locator('#activityExitBtn').click();
    await page.waitForFunction(() => !ChatApp.gamesStageOpen);
    assert.equal(await page.locator('.chat-main').isVisible(),true);
    assert.equal(await page.locator('#merge-party-paused-frame').count(),1);
    // Open and close the other game while the local run is parked.
    await page.evaluate(() => ChatApp.openBoplRoyaleActivity('test'));
    await page.waitForFunction(() => document.querySelector('#games-frame')?.contentWindow?.__boplRoyale);
    assert.equal(await page.frameLocator('#games-frame').locator('#activityChatBtn').isVisible(),true);
    assert.equal(await page.frameLocator('#games-frame').locator('#pauseBtn').count(),0);
    await page.frameLocator('#games-frame').locator('#activityChatBtn').click();
    await page.waitForFunction(() => document.body.dataset.activityChat === '1');
    await page.frameLocator('#games-frame').locator('#activityExitBtn').click();
    await page.waitForFunction(() => !ChatApp.gamesStageOpen);
    await page.evaluate(() => ChatApp.openMergePartyActivity('test'));
    await page.waitForFunction(() => document.querySelector('#games-frame')?.contentWindow?.__mergeParty);
    assert.equal(await page.evaluate(() => __mergeFrame === document.querySelector('#games-frame') && __mergeWindow === document.querySelector('#games-frame').contentWindow),true,'parked frame must never reload');
    assert.equal(await page.evaluate(() => JSON.stringify(__mergeWindow.__mergeParty.debug.getState().balls)),paused);
    assert.equal(await page.evaluate(() => __mergeWindow.__mergeParty.isPaused()),true);
    await page.frameLocator('#games-frame').locator('#resumeBtn').click();
    assert.equal(await page.evaluate(() => __mergeWindow.__mergeParty.isPaused()),false);
    await page.evaluate(() => ChatApp.setActivityChatOpen(true));
    await page.setViewportSize({width:390,height:844});
    await page.waitForTimeout(200);
    box = await page.locator('.chat-main').boundingBox();
    assert.equal(Math.round(box.width),117);
    assert.ok(await page.locator('#msg-input').isVisible());
    await page.screenshot({path:path.join(root,'../activity-chat-mobile.png')});
    await page.evaluate(() => ChatApp.closeToast());
    await page.locator('#activity-chat-resize').focus();
    await page.keyboard.press('Home');
    await page.waitForTimeout(150);
    box = await page.locator('.chat-main').boundingBox();
    assert.equal(box.width,58.5);
    for (const selector of ['#btn-send','#btn-composer-more','#msg-input']) {
      const control = await page.locator(selector).boundingBox();
      assert.ok(control.x >= box.x && control.x + control.width <= box.x + box.width,`${selector} must fit the narrowest chat`);
    }
    await page.screenshot({path:path.join(root,'../activity-chat-mobile-min.png')});
    assert.equal(await page.evaluate(() => getComputedStyle(document.querySelector('.app')).position),'static','activity chat must escape the mobile fixed app stacking context');
    await page.evaluate(() => { ChatApp.activityChatWidth=30; ChatApp.syncActivityChatLayout(); ChatApp.toggleMembersListVisibility(); });
    await page.waitForTimeout(250);
    members = await page.locator('#members-sidebar').boundingBox();
    assert.equal(Math.round(members.width),117);
    assert.equal(Math.round(members.x),0);
    await page.locator('#activity-chat-members-back').click();
    assert.deepEqual(errors,[]);
    console.log('Activity integration passed: live picker, original chat, both positions, 15–30% resize, members, mobile, Merge pause/switch/resume and Bopl exit.');
    await context.close();
  } finally { await browser.close(); server.close(); }
})().catch(error => { console.error(error); server.close(); process.exitCode = 1; });
